from datetime import date


DATE_FORMAT = "%Y-%m-%d"
DEFAULT_RECURRING_END = date(2100, 1, 1)
ID_ALPHABET = "123456789ABCDEF"
ID_LENGTH = 6

TASK_KIND_ONE_TIME = "one_time"
TASK_KIND_RECURRING = "recurring"

REPEAT_DAY = "day"
REPEAT_WEEK = "week"
REPEAT_MONTH = "month"
REPEAT_YEAR = "year"
VALID_REPEAT_UNITS = {REPEAT_DAY, REPEAT_WEEK, REPEAT_MONTH, REPEAT_YEAR}

STATUS_TODO = "todo"
STATUS_DOING = "doing"
STATUS_DONE = "done"
VALID_STATUSES = {STATUS_TODO, STATUS_DOING, STATUS_DONE}
